"""make text required

Revision ID: 055148e10e32
Revises: 83f7da90bf17
Create Date: 2022-07-18 22:34:02.521326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055148e10e32'
down_revision = '83f7da90bf17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
