"""make id integer

Revision ID: 2be31467362d
Revises: d86ae8a4f11b
Create Date: 2022-07-20 12:47:23.940338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be31467362d'
down_revision = 'd86ae8a4f11b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
