"""make done not nullable

Revision ID: 669fa5ce0dfa
Revises: a35cb0bad13d
Create Date: 2022-07-20 23:56:27.934052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669fa5ce0dfa'
down_revision = 'a35cb0bad13d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'done',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'done',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
