"""rollback

Revision ID: 76377dda245a
Revises: 669fa5ce0dfa
Create Date: 2022-07-21 00:00:35.217693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76377dda245a'
down_revision = '669fa5ce0dfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'done',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'done',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
