"""import databases

Revision ID: 83b868e28aa4
Revises: 2be31467362d
Create Date: 2022-07-20 23:35:07.190334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b868e28aa4'
down_revision = '2be31467362d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
