"""make text optional

Revision ID: 83f7da90bf17
Revises: a9adbaa5be63
Create Date: 2022-07-18 22:32:22.319960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f7da90bf17'
down_revision = 'a9adbaa5be63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
