"""make date instead of datetime

Revision ID: a35cb0bad13d
Revises: 83b868e28aa4
Create Date: 2022-07-20 23:41:14.341499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a35cb0bad13d'
down_revision = '83b868e28aa4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('deadline', sa.Date(), nullable=False))
    op.drop_column('tasks', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'deadline')
    # ### end Alembic commands ###
