"""make id UUID

Revision ID: d86ae8a4f11b
Revises: fb50761c64a9
Create Date: 2022-07-20 12:43:03.452968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86ae8a4f11b'
down_revision = 'fb50761c64a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
