"""make text optional

Revision ID: fb50761c64a9
Revises: 055148e10e32
Create Date: 2022-07-19 12:46:41.493238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb50761c64a9'
down_revision = '055148e10e32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tasks', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tasks', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
